### ISSUE TITLE
Invitation to move to official `eslint-community` org

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint-community/eslint-plugin-rulesdir#11]
[Original posting by `not-an-aardvark` in the Discord channel](https://discord.com/channels/688543509199716507/711686958635548723/1242230393957253221): 

> Hi folks! Hope everyone's been doing well.
>
> I no longer have time to maintain this plugin: https://github.com/not-an-aardvark/eslint-plugin-rulesdir
>
> My understanding is that it still has some users, but I'm not sure how many. According to npm, it gets 260k downloads/week.
>
> Is there any interest in having me transfer this repo to the https://github.com/eslint-community organization? If not, I'll probably archive the repo and recommend that people fork it.
>
> (I'm not sure if eslint-community@ is still accepting new repos at all, or whether this repo is a good fit for it. I haven't really kept up-to-date with plugin ecosystem changes over the past few years. But I figured I would ask before archiving the repo.)

@not-an-aardvark As you're already member of the org, you can just transfer the repo whenever you're ready to do so

**Comment by not-an-aardvark** [comment]
Thanks, I've transferred the repo.
